// Public barrel for the game module (simulation core, entities, world, state, engine). Track P0.
export * from './core/Types';
export * from './core/math';
export { Random } from './core/Random';
export * from './core/Transform';
export { EventBus } from './core/EventBus';
export type { GameEvents } from './core/EventBus';
export { Input, DEFAULT_BINDINGS } from './core/Input';
export type { Action } from './core/Input';
export { SpatialHash } from './core/SpatialHash';
export type { HashItem } from './core/SpatialHash';
export * from './core/Collision';
export { GameLoop } from './core/GameLoop';
export type { LoopCallbacks } from './core/GameLoop';
export { BUDGET } from './core/Budget';
export { GameStore, DEFAULT_SETTINGS, initialHudState } from './state/GameStore';
export type { Settings, Notification, DebugStats, HudState } from './state/GameStore';
export { nextEntityId, resetEntityIds } from './entities/Entity';
export type { Entity, EntityKind } from './entities/Entity';
export { SPECS, TRAFFIC_MIX } from './entities/VehicleSpecs';
export type { VehicleKey, VehicleSpec } from './entities/VehicleSpecs';
export { Vehicle, makeTrafficBrain, makePoliceBrain } from './entities/Vehicle';
export type { TrafficBrain, PoliceBrain } from './entities/Vehicle';
export { Pedestrian } from './entities/Pedestrian';
export { Player } from './entities/Player';
export * from './city/CityConfig';
export type * from './city/CityData';
export * from './city/Palette';
export { RoadGraph } from './city/RoadGraph';
export type { RoadNode, RoadSegment, Lane, LanePos, Occupant } from './city/RoadGraph';
export { SidewalkGraph } from './city/SidewalkGraph';
export type { WalkNode } from './city/SidewalkGraph';
export { generateCity, validateCity } from './city/CityGenerator';
export type { GeneratedCity } from './city/CityGenerator';
export { World } from './world/World';
export type { WantedState, MissionState, HudSignals } from './world/World';
export { stubCamera, stubAudio } from './systems/System';
export type { System, EngineContext, CameraLike, AudioLike, UiSound } from './systems/System';
export { createMinimapSnapshot, MinimapRenderer } from './minimap/MinimapRenderer';
export type { MinimapSnapshot, Blip, BlipKind } from './minimap/MinimapRenderer';
export { Engine, parseEngineOptions } from './Engine';
export type { EngineOptions } from './Engine';
